### ISSUE TITLE
Example for RabbitMQ or is it broken?

### ISSUE THREAD

**Issue by janpieper** [gmtprime/yggdrasil#2]
**config/dev.exs**

```
config :yggdrasil,
  rabbitmq: [host: "127.0.0.1",
    port: 5672,
    username: "dwalin",
    password: "dwalin",
    virtual_host: "/"]
```

**iex -S mix**

```
iex(1)> Application.ensure_started(:yggdrasil)
:ok
iex(2)> Application.ensure_started(:dwalin)
:ok
```

``` elixir
channel = %Yggdrasil.Channel{channel: "example", decoder: Yggdrasil.Decoder.Default.RabbitMQ}
Yggdrasil.subscribe(channel)
```

```
[debug] Started publisher for %Yggdrasil.Channel{channel: "example", decoder: Yggdrasil.Decoder.Default.RabbitMQ}.
** (exit) exited in: GenServer.call(Yggdrasil.Broker, {:subscribe, %Yggdrasil.Channel{channel: "example", decoder: Yggdrasil.Decoder.Default.RabbitMQ}, #PID<0.264.0>}, 5000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:shutdown, {:failed_to_start_child, Yggdrasil.Adapter.RabbitMQ, {:function_clause, [{Yggdrasil.Adapter.RabbitMQ, :init, [%Yggdrasil.Adapter{channel: "example", publisher: {:via, ExReg, {Yggdrasil.Publisher, "example", Yggdrasil.Decoder.Default.RabbitMQ}}}], [file: 'lib/yggdrasil/adapter/rabbitmq.ex', line: 28]}, {Connection, :init_it, 6, [file: 'lib/connection.ex', line: 424]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}}}
            (yggdrasil) lib/yggdrasil/publisher/generator.ex:40: Yggdrasil.Publisher.Generator.start_publisher/2
            (yggdrasil) lib/yggdrasil/broker.ex:198: Yggdrasil.Broker.do_subscribe/3
            (yggdrasil) lib/yggdrasil/broker.ex:303: Yggdrasil.Broker.handle_call/3
            (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
[error] GenServer Yggdrasil.Broker terminating
** (MatchError) no match of right hand side value: {:error, {:shutdown, {:failed_to_start_child, Yggdrasil.Adapter.RabbitMQ, {:function_clause, [{Yggdrasil.Adapter.RabbitMQ, :init, [%Yggdrasil.Adapter{channel: "example", publisher: {:via, ExReg, {Yggdrasil.Publisher, "example", Yggdrasil.Decoder.Default.RabbitMQ}}}], [file: 'lib/yggdrasil/adapter/rabbitmq.ex', line: 28]}, {Connection, :init_it, 6, [file: 'lib/connection.ex', line: 424]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}}}
    (yggdrasil) lib/yggdrasil/publisher/generator.ex:40: Yggdrasil.Publisher.Generator.start_publisher/2
    (yggdrasil) lib/yggdrasil/broker.ex:198: Yggdrasil.Broker.do_subscribe/3
    (yggdrasil) lib/yggdrasil/broker.ex:303: Yggdrasil.Broker.handle_call/3
    (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:subscribe, %Yggdrasil.Channel{channel: "example", decoder: Yggdrasil.Decoder.Default.RabbitMQ}, #PID<0.264.0>}
State: %Yggdrasil.Broker{generator: Yggdrasil.Publisher.Generator, monitors: 94246, subscribers: 98343}
       (elixir) lib/gen_server.ex:604: GenServer.call/3
    (yggdrasil) lib/yggdrasil/backend.ex:55: Yggdrasil.Backend.join/2
```

**Comment by alexdesousa** [comment]
@janpieper Hey! It shouldn't be broken. The thing is you are using an incorrect channel with that adapter. The channel should be something like `{"exchange", "routing_key"}` and the exchange has topic type. So you could have something like `{"messages", "errors.*"}` where the routing key would match `"errors.critical"`, `"errors.normal"`, etc.

So instead of using the channel:

``` elixir
channel = %Yggdrasil.Channel{channel: "example", decoder: Yggdrasil.Decoder.Default.RabbitMQ}
```

use

``` elixir
channel = %Yggdrasil.Channel{channel: {"test_exchange", "example"}, decoder: Yggdrasil.Decoder.Default.RabbitMQ}
```

I should have written an example with RabbitMQ, so I'll close this issue when I've written the example.

Thanks :)

**Comment by alexdesousa** [comment]
@janpieper Writing the example for the documentation, I noticed an annoying bug in the RabbitMQ adapter. Right now the version 2.0.1 has the fix. Also the examples are now in the documentation.

**Comment by janpieper** [comment]
Thanks!
